use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::backend::{Backend, BackendReport, BridgeReport};
use crate::config::{parse_python_requirement, Config};
use crate::errors::DualError;
use crate::platform;

const MANAGED_HEADER: &str = "# This file is generated by dual.\n# Edit dual.toml instead.\n\n";
const BACKEND_LOCK_NAME: &str = "pixi.lock";
const PAK_LOCK_NAME: &str = "pak.lock";
const ENGINE_VERSION: &str = "0.70.2";

#[derive(Clone, Debug)]
pub struct EnvironmentBackend {
    root: PathBuf,
    verbose: bool,
}

impl EnvironmentBackend {
    pub fn new(root: &Path, verbose: bool) -> Self {
        Self {
            root: root.to_owned(),
            verbose,
        }
    }

    fn state_dir(&self) -> PathBuf {
        self.root.join(".dual")
    }

    fn workspace_dir(&self) -> PathBuf {
        self.state_dir().join("workspace")
    }

    fn manifest_path(&self) -> PathBuf {
        self.workspace_dir().join("pyproject.toml")
    }

    fn backend_lock_path(&self) -> PathBuf {
        self.workspace_dir().join(BACKEND_LOCK_NAME)
    }

    fn backend_metadata_path(&self) -> PathBuf {
        self.workspace_dir().join(".pixi")
    }

    fn public_lock_path(&self) -> PathBuf {
        self.root.join("dual.lock")
    }

    fn staged_pak_lock_path(&self) -> PathBuf {
        self.workspace_dir().join(PAK_LOCK_NAME)
    }

    fn ready_path(&self) -> PathBuf {
        self.state_dir().join("ready")
    }

    fn bridge_dir(&self) -> PathBuf {
        self.state_dir().join("bridge")
    }

    fn config_path(&self) -> PathBuf {
        self.state_dir().join("engine.toml")
    }

    fn engine_home(&self) -> PathBuf {
        env::var_os("DUAL_HOME")
            .map(PathBuf::from)
            .unwrap_or_else(default_dual_home)
            .join("engine")
    }

    fn managed_engine_path(&self) -> PathBuf {
        self.engine_home().join("bin").join(engine_binary_name())
    }

    fn engine_path(&self) -> Option<PathBuf> {
        env::var_os("DUAL_ENGINE_PATH")
            .map(PathBuf::from)
            .filter(|path| path.is_file())
            .or_else(|| {
                let path = self.managed_engine_path();
                path.is_file().then_some(path)
            })
            .or_else(|| {
                env::var_os("DUAL_ENGINE_DISABLE_PATH_FALLBACK")
                    .is_none()
                    .then(|| which::which("pixi").ok())
                    .flatten()
            })
    }

    fn engine_command(&self) -> Result<Command> {
        let path = self.engine_path().ok_or_else(|| {
            DualError::BackendStart("environment support has not been installed yet".to_owned())
        })?;
        let mut command = Command::new(path);
        command.current_dir(&self.root);
        Ok(command)
    }

    fn configured_command(&self, args: &[&str]) -> Result<Command> {
        let mut command = self.engine_command()?;
        if let Some((subcommand, rest)) = args.split_first() {
            command
                .arg(subcommand)
                .arg("--config-file")
                .arg(self.config_path())
                .args(rest);
        }
        Ok(command)
    }

    fn install_engine(&self) -> Result<()> {
        println!("Installing environment support...");
        fs::create_dir_all(self.engine_home().join("bin"))
            .context("could not create dual's environment support directory")?;

        self.download_engine()?;

        if !self.managed_engine_path().is_file() {
            anyhow::bail!(
                "Environment support could not be installed. Check your network connection \
                 and try `dual up` again."
            );
        }
        println!("✓ Environment support installed");
        Ok(())
    }

    fn download_engine(&self) -> Result<()> {
        let asset = engine_asset()?;
        let url = env::var("DUAL_ENGINE_DOWNLOAD_URL").unwrap_or_else(|_| asset.url.to_owned());
        let expected = env::var("DUAL_ENGINE_SHA256")
            .unwrap_or_else(|_| asset.sha256.to_owned())
            .to_ascii_lowercase();
        let temporary = self
            .engine_home()
            .join("bin")
            .join(format!("dual-engine.download-{}", unique_suffix()));
        download_file(&url, &temporary)
            .context("could not download environment support; check your network connection")?;
        let actual = sha256_file(&temporary)?;
        if actual != expected {
            let _ = fs::remove_file(&temporary);
            anyhow::bail!(
                "Environment support failed its integrity check. Expected {expected}, got {actual}."
            );
        }

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut permissions = fs::metadata(&temporary)?.permissions();
            permissions.set_mode(0o755);
            fs::set_permissions(&temporary, permissions)?;
        }

        let destination = self.managed_engine_path();
        if destination.is_file() {
            fs::remove_file(&destination)?;
        }
        fs::rename(&temporary, &destination)
            .context("could not activate the verified environment support executable")
    }

    fn prepare_state(&self) -> Result<()> {
        fs::create_dir_all(self.workspace_dir())
            .context("could not create the internal environment workspace")?;
        let environments = self.state_dir().join("environments");
        let config = format!(
            "detached-environments = {:?}\n",
            environments.to_string_lossy()
        );
        fs::write(self.config_path(), config)
            .context("could not write the internal environment configuration")?;
        Ok(())
    }

    fn stage_lock(&self) -> Result<()> {
        self.clear_backend_lock()?;
        if self.public_lock_path().is_file() {
            let lock = read_dual_lock(&self.public_lock_path())?;
            fs::write(self.backend_lock_path(), lock.environment)
                .context("could not stage the environment resolution from dual.lock")?;
        }
        Ok(())
    }

    fn finish_lock(&self) -> Result<()> {
        self.clear_backend_lock()?;
        self.clear_backend_metadata()?;
        clear_engine_markers(&self.state_dir())?;
        Ok(())
    }

    fn clear_backend_lock(&self) -> Result<()> {
        if self.backend_lock_path().is_file() {
            fs::remove_file(self.backend_lock_path())
                .context("could not remove the temporary engine lock")?;
        }
        Ok(())
    }

    fn clear_backend_metadata(&self) -> Result<()> {
        let path = self.backend_metadata_path();
        if path.is_dir() {
            fs::remove_dir_all(path).context("could not remove temporary engine metadata")?;
        }
        Ok(())
    }

    fn manifest_arg(&self) -> String {
        self.manifest_path().to_string_lossy().into_owned()
    }

    fn execute(&self, args: &[&str], friendly_action: &str) -> Result<()> {
        let mut command = self.configured_command(args)?;
        if self.verbose {
            eprintln!("engine: {}", friendly_action.to_ascii_lowercase());
        }

        command.stdout(Stdio::piped()).stderr(Stdio::piped());
        let output = command
            .output()
            .map_err(|error| DualError::BackendStart(error.to_string()))?;
        if !output.status.success() {
            let detail = sanitized_engine_error(&output.stderr);
            anyhow::bail!(
                "{friendly_action} failed.{}",
                if detail.is_empty() {
                    String::new()
                } else {
                    format!("\n{detail}")
                }
            );
        } else if self.verbose && !output.stderr.is_empty() {
            let detail = sanitized_engine_error(&output.stderr);
            if !detail.is_empty() {
                eprintln!("{detail}");
            }
        }
        Ok(())
    }

    fn execute_task(&self, args: &[&str], task: &str) -> Result<()> {
        let output = self
            .configured_command(args)?
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .output()
            .map_err(|error| DualError::BackendStart(error.to_string()))?;
        io::stdout().write_all(&output.stdout)?;
        io::stdout().flush()?;
        let stderr = sanitized_task_stderr(&output.stderr);
        if !stderr.is_empty() {
            eprintln!("{stderr}");
        }
        if !output.status.success() {
            anyhow::bail!("Task `{task}` failed.");
        }
        Ok(())
    }

    fn capture(&self, args: &[&str]) -> Result<Output> {
        if self.verbose {
            eprintln!("engine: checking project environment");
        }
        self.configured_command(args)?
            .output()
            .map_err(|error| DualError::BackendStart(error.to_string()).into())
    }

    fn run_check(&self, command: &[&str]) -> bool {
        let manifest = self.manifest_arg();
        let mut args = vec![
            "run",
            "--manifest-path",
            &manifest,
            "--locked",
            "--executable",
        ];
        args.extend(command);
        if self.stage_lock().is_err() {
            return false;
        }
        let succeeded = self
            .capture(&args)
            .map(|output| output.status.success())
            .unwrap_or(false);
        let _ = self.finish_lock();
        succeeded
    }

    fn missing_r_packages(&self, packages: &[String]) -> Vec<String> {
        packages
            .iter()
            .filter(|package| {
                let Some(name) = r_package_name(package) else {
                    return true;
                };
                let expression = format!(
                    "quit(status=ifelse(requireNamespace('{}', quietly=TRUE), 0, 1))",
                    escape_r_string(&name)
                );
                !self.run_check(&["Rscript", "-e", &expression])
            })
            .cloned()
            .collect()
    }

    fn missing_python_packages(&self, packages: &[String]) -> Vec<String> {
        packages
            .iter()
            .filter(|package| {
                let Ok(requirement) = parse_python_requirement(package) else {
                    return true;
                };
                let expression = format!(
                    "import importlib.metadata as m; m.version({:?})",
                    requirement.name
                );
                !self.run_check(&["python", "-c", &expression])
            })
            .cloned()
            .collect()
    }

    fn install_source_r_packages(
        &self,
        config: &Config,
        existing_lock: Option<&DualLock>,
        refresh: bool,
    ) -> Result<Option<RSourceLock>> {
        let packages = source_r_packages(config);
        if packages.is_empty() {
            if existing_lock.is_some_and(|lock| lock.r.is_some()) && !refresh {
                anyhow::bail!(
                    "dual.lock does not match dual.toml. Run `dual up --refresh` \
                     to remove the obsolete R source resolution."
                );
            }
            return Ok(None);
        }

        let staged_lock = self.staged_pak_lock_path();
        if staged_lock.is_file() {
            fs::remove_file(&staged_lock)?;
        }

        let locked_r = existing_lock.and_then(|lock| lock.r.as_ref());
        let use_existing_lock = locked_r.is_some() && !refresh;
        if let Some(lock) = locked_r.filter(|_| !refresh) {
            let requested = packages
                .iter()
                .map(|package| (*package).to_owned())
                .collect::<Vec<_>>();
            if lock.sources != requested {
                anyhow::bail!(
                    "dual.lock does not match dual.toml. Run `dual up --refresh` \
                     to update the R source resolution."
                );
            }
            write_json(&staged_lock, &lock.pak)
                .context("could not stage the R source resolution from dual.lock")?;
        }

        let expression = if use_existing_lock {
            format!(
                "pak::lockfile_install(lockfile={}, lib=.libPaths()[1], update=TRUE)",
                r_string_literal(&staged_lock.to_string_lossy())
            )
        } else {
            let refs = packages
                .iter()
                .map(|package| r_string_literal(package))
                .collect::<Vec<_>>()
                .join(", ");
            format!(
                concat!(
                    "pak::lockfile_create(pkg=c({refs}), lockfile={lock}, ",
                    "lib=.libPaths(), upgrade={upgrade}); ",
                    "pak::lockfile_install(lockfile={lock}, lib=.libPaths()[1], update=TRUE)"
                ),
                refs = refs,
                lock = r_string_literal(&staged_lock.to_string_lossy()),
                upgrade = if refresh { "TRUE" } else { "FALSE" },
            )
        };

        let manifest = self.manifest_arg();
        let result = self.execute(
            &[
                "run",
                "--manifest-path",
                &manifest,
                "--locked",
                "--executable",
                "Rscript",
                "-e",
                &expression,
            ],
            "Installing source-backed R packages",
        );

        let resolved = if result.is_ok() {
            if use_existing_lock {
                locked_r.cloned()
            } else {
                let pak = read_json(&staged_lock)
                    .context("pak did not produce a readable R source resolution")?;
                Some(RSourceLock {
                    sources: packages
                        .iter()
                        .map(|package| (*package).to_owned())
                        .collect(),
                    pak,
                })
            }
        } else {
            None
        };
        if staged_lock.is_file() {
            fs::remove_file(staged_lock)?;
        }
        result.with_context(|| {
            if use_existing_lock {
                "The R source resolution from dual.lock could not be restored. Run `dual up --refresh` to re-resolve it."
            } else {
                "CRAN, Bioconductor, or GitHub R packages could not be resolved."
            }
        })?;
        Ok(resolved)
    }

    fn prepare_bridge(&self) -> Result<()> {
        self.stage_lock()?;
        let manifest = self.manifest_arg();
        let bridge = self.bridge_dir().to_string_lossy().into_owned();
        let output = self.capture(&[
            "run",
            "--manifest-path",
            &manifest,
            "--locked",
            "--executable",
            "python",
            "-m",
            "venv",
            "--clear",
            "--system-site-packages",
            &bridge,
        ]);
        self.finish_lock()?;
        if !output?.status.success() {
            anyhow::bail!("Could not prepare the R/Python bridge.");
        }
        Ok(())
    }
}

impl Backend for EnvironmentBackend {
    fn is_available(&self) -> bool {
        self.engine_path().is_some()
    }

    fn ensure_available(&self) -> Result<()> {
        if self.is_available() {
            return Ok(());
        }
        self.install_engine()
    }

    fn environment_exists(&self) -> bool {
        self.ready_path().is_file() && self.manifest_path().is_file()
    }

    fn init_or_update(&self, config: &Config, refresh: bool) -> Result<()> {
        self.prepare_state()?;
        if self.ready_path().is_file() {
            fs::remove_file(self.ready_path())?;
        }
        let existing_lock = if self.public_lock_path().is_file() && !refresh {
            Some(read_dual_lock(&self.public_lock_path())?)
        } else {
            None
        };
        let generated = generate_manifest(config)?;
        if self.manifest_path().exists() {
            let existing = fs::read_to_string(self.manifest_path())
                .context("could not inspect the internal environment manifest")?;
            if !existing.starts_with(MANAGED_HEADER) {
                anyhow::bail!(
                    "The internal environment manifest was not generated by dual. \
                     Run `dual clean --yes`, then try `dual up` again."
                );
            }
        }
        let use_locked_install = should_use_locked_install(existing_lock.is_some(), refresh);

        fs::write(self.manifest_path(), generated)
            .context("could not write generated environment configuration")?;
        if refresh {
            self.clear_backend_lock()?;
        } else {
            self.stage_lock()?;
        }
        let manifest = self.manifest_arg();
        let args = if use_locked_install {
            vec!["install", "--manifest-path", &manifest, "--locked"]
        } else {
            vec!["install", "--manifest-path", &manifest]
        };
        let result = self
            .execute(&args, "Preparing the project environment")
            .with_context(|| {
                if use_locked_install {
                    return "The shared lockfile does not match dual.toml. \
                        If dual.toml was intentionally changed, run \
                        `dual up --refresh` to update dual.lock."
                        .to_owned();
                }
                let inferred = config
                    .r
                    .packages
                    .iter()
                    .filter(|package| !known_r_mapping(package))
                    .cloned()
                    .collect::<Vec<_>>();
                if inferred.is_empty() {
                    "The requested package set could not be resolved.".to_owned()
                } else {
                    format!(
                        "Some R package names used inferred conda-forge names: {}.",
                        inferred.join(", ")
                    )
                }
            });
        if result.is_ok() {
            let finalize = (|| {
                let pixi = fs::read_to_string(self.backend_lock_path())
                    .context("the environment engine did not produce a lock resolution")?;
                let r = self.install_source_r_packages(config, existing_lock.as_ref(), refresh)?;
                write_dual_lock(
                    &self.public_lock_path(),
                    &DualLock {
                        version: 1,
                        environment: pixi,
                        r,
                    },
                )
            })();
            if let Err(error) = finalize {
                self.finish_lock()?;
                return Err(error);
            }
            self.finish_lock()?;
            if config
                .r
                .packages
                .iter()
                .filter_map(|package| r_package_name(package))
                .any(|package| package.eq_ignore_ascii_case("reticulate"))
            {
                self.prepare_bridge()?;
            }
            fs::write(self.ready_path(), "ready\n")?;
        } else {
            self.finish_lock()?;
        }
        result
    }

    fn validate(&self, config: &Config) -> Result<()> {
        if !self.run_check(&["Rscript", "--version"]) {
            anyhow::bail!("R could not start inside the project environment.");
        }
        if !self.run_check(&["python", "--version"]) {
            anyhow::bail!("Python could not start inside the project environment.");
        }

        if config
            .r
            .packages
            .iter()
            .filter_map(|package| r_package_name(package))
            .any(|package| package.eq_ignore_ascii_case("reticulate"))
        {
            let check = concat!(
                "library(reticulate); ",
                "configured <- normalizePath(Sys.getenv('RETICULATE_PYTHON'), ",
                "winslash='/', mustWork=FALSE); ",
                "actual <- normalizePath(py_config()$python, winslash='/', mustWork=FALSE); ",
                "quit(status=ifelse(nzchar(configured) && ",
                "identical(tolower(configured), tolower(actual)), 0, 1))"
            );
            if !self.run_check(&["Rscript", "-e", check]) {
                anyhow::bail!(
                    "R and Python are installed, but the R/Python bridge could not use \
                     the project Python."
                );
            }
        }
        Ok(())
    }

    fn run(&self, task: &str) -> Result<()> {
        self.stage_lock()?;
        let manifest = self.manifest_arg();
        let result = self.execute_task(
            &["run", "--manifest-path", &manifest, "--locked", task],
            task,
        );
        self.finish_lock()?;
        result
    }

    fn shell(&self) -> Result<()> {
        self.stage_lock()?;
        let manifest = self.manifest_arg();
        let (shell, shell_args) = platform::default_shell();
        let mut owned_args = vec![
            "run".to_owned(),
            "--manifest-path".to_owned(),
            manifest,
            "--locked".to_owned(),
            "--executable".to_owned(),
            shell,
        ];
        owned_args.extend(shell_args);
        let args = owned_args.iter().map(String::as_str).collect::<Vec<_>>();
        if self.verbose {
            eprintln!("engine: opening project shell");
        }
        let status = self
            .configured_command(&args)?
            .stdin(Stdio::inherit())
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit())
            .status()
            .map_err(|error| DualError::BackendStart(error.to_string()))?;
        if !status.success() {
            self.finish_lock()?;
            return Err(DualError::BackendFailed(status.to_string()).into());
        }
        self.finish_lock()?;
        Ok(())
    }

    fn clean(&self) -> Result<Vec<PathBuf>> {
        let mut removed = Vec::new();
        for path in platform::managed_paths(&self.root) {
            if path.is_dir() {
                fs::remove_dir_all(&path)
                    .with_context(|| format!("could not remove {}", path.display()))?;
                removed.push(path);
            } else if path.is_file() {
                fs::remove_file(&path)
                    .with_context(|| format!("could not remove {}", path.display()))?;
                removed.push(path);
            }
        }
        Ok(removed)
    }

    fn doctor(&self, config: &Config) -> Result<BackendReport> {
        let available = self.is_available();
        let environment_present = self.environment_exists();
        let lock_present = self.public_lock_path().is_file();
        if !available || !environment_present {
            return Ok(BackendReport {
                available,
                environment_present,
                lock_present,
                ..BackendReport::default()
            });
        }

        let r_available = self.run_check(&["Rscript", "--version"]);
        let python_available = self.run_check(&["python", "--version"]);
        let missing_r_packages = if r_available {
            self.missing_r_packages(&config.r.packages)
        } else {
            Vec::new()
        };
        let missing_python_packages = if python_available {
            self.missing_python_packages(&config.python.packages)
        } else {
            Vec::new()
        };

        let bridge = if r_available && python_available {
            let reticulate_installed = self.run_check(&[
                "Rscript",
                "-e",
                "quit(status=ifelse(requireNamespace('reticulate', quietly=TRUE), 0, 1))",
            ]);
            let uses_project_python = reticulate_installed
                && self.run_check(&[
                    "Rscript",
                    "-e",
                    concat!(
                        "library(reticulate); ",
                        "configured <- normalizePath(Sys.getenv('RETICULATE_PYTHON'), ",
                        "winslash='/', mustWork=FALSE); ",
                        "actual <- normalizePath(py_config()$python, winslash='/', mustWork=FALSE); ",
                        "quit(status=ifelse(nzchar(configured) && ",
                        "identical(tolower(configured), tolower(actual)), 0, 1))"
                    ),
                ]);
            Some(BridgeReport {
                reticulate_installed,
                uses_project_python,
            })
        } else {
            None
        };

        Ok(BackendReport {
            available,
            environment_present,
            lock_present,
            r_available: Some(r_available),
            python_available: Some(python_available),
            missing_r_packages,
            missing_python_packages,
            bridge,
        })
    }
}

#[derive(Serialize)]
struct PyProject {
    project: PyProjectMetadata,
    tool: ToolTable,
}

#[derive(Serialize)]
struct PyProjectMetadata {
    name: String,
    version: String,
}

#[derive(Serialize)]
struct ToolTable {
    pixi: PixiManifest,
}

#[derive(Serialize)]
struct PixiManifest {
    workspace: Workspace,
    dependencies: BTreeMap<String, String>,
    #[serde(rename = "pypi-dependencies")]
    pypi_dependencies: BTreeMap<String, PypiDependency>,
    tasks: BTreeMap<String, TaskSpec>,
    target: BTreeMap<String, TargetConfig>,
}

#[derive(Serialize)]
#[serde(untagged)]
enum PypiDependency {
    Version(String),
    Detailed {
        version: String,
        extras: Vec<String>,
    },
}

#[derive(Serialize)]
struct Workspace {
    name: String,
    channels: Vec<String>,
    platforms: Vec<String>,
}

#[derive(Serialize)]
struct TaskSpec {
    cmd: String,
    cwd: String,
}

#[derive(Serialize)]
struct TargetConfig {
    activation: Activation,
}

#[derive(Serialize)]
struct Activation {
    env: BTreeMap<String, String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
struct DualLock {
    version: u8,
    #[serde(alias = "pixi")]
    environment: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    r: Option<RSourceLock>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
struct RSourceLock {
    sources: Vec<String>,
    pak: serde_json::Value,
}

pub fn generate_manifest(config: &Config) -> Result<String> {
    let mut dependencies = BTreeMap::new();
    dependencies.insert("r-base".to_owned(), version_constraint(&config.r.version));
    dependencies.insert(
        "python".to_owned(),
        version_constraint(&config.python.version),
    );
    for package in conda_r_packages(config) {
        dependencies.insert(r_conda_name(package), "*".to_owned());
    }
    if !source_r_packages(config).is_empty() {
        dependencies.insert("r-pak".to_owned(), "*".to_owned());
    }

    let pypi_dependencies = config
        .python
        .packages
        .iter()
        .map(|package| {
            let requirement = parse_python_requirement(package)?;
            let dependency = if requirement.extras.is_empty() {
                PypiDependency::Version(requirement.version)
            } else {
                PypiDependency::Detailed {
                    version: requirement.version,
                    extras: requirement.extras,
                }
            };
            Ok((requirement.name, dependency))
        })
        .collect::<Result<BTreeMap<_, _>>>()?;

    let manifest = PyProject {
        project: PyProjectMetadata {
            name: config.project.name.clone(),
            version: "0.0.0".to_owned(),
        },
        tool: ToolTable {
            pixi: PixiManifest {
                workspace: Workspace {
                    name: config.project.name.clone(),
                    channels: vec!["conda-forge".to_owned()],
                    platforms: vec![
                        "linux-64".to_owned(),
                        "osx-64".to_owned(),
                        "osx-arm64".to_owned(),
                        "win-64".to_owned(),
                    ],
                },
                dependencies,
                pypi_dependencies,
                tasks: config
                    .tasks
                    .iter()
                    .map(|(name, command)| {
                        (
                            name.clone(),
                            TaskSpec {
                                cmd: command.clone(),
                                cwd: "../..".to_owned(),
                            },
                        )
                    })
                    .collect(),
                target: BTreeMap::from([
                    (
                        "unix".to_owned(),
                        TargetConfig {
                            activation: Activation {
                                env: BTreeMap::from([
                                    (
                                        "RETICULATE_PYTHON".to_owned(),
                                        "$PIXI_PROJECT_ROOT/../bridge/bin/python".to_owned(),
                                    ),
                                    ("RETICULATE_USE_MANAGED_VENV".to_owned(), "no".to_owned()),
                                ]),
                            },
                        },
                    ),
                    (
                        "win".to_owned(),
                        TargetConfig {
                            activation: Activation {
                                env: BTreeMap::from([
                                    (
                                        "RETICULATE_PYTHON".to_owned(),
                                        "%PIXI_PROJECT_ROOT%\\..\\bridge\\Scripts\\python.exe"
                                            .to_owned(),
                                    ),
                                    ("RETICULATE_USE_MANAGED_VENV".to_owned(), "no".to_owned()),
                                ]),
                            },
                        },
                    ),
                ]),
            },
        },
    };

    Ok(format!(
        "{MANAGED_HEADER}{}",
        toml::to_string_pretty(&manifest)?
    ))
}

fn version_constraint(version: &str) -> String {
    if version
        .chars()
        .any(|character| matches!(character, '*' | '<' | '>' | '=' | '~' | '^'))
    {
        version.to_owned()
    } else {
        format!("{version}.*")
    }
}

fn r_conda_name(package: &str) -> String {
    match package.to_ascii_lowercase().as_str() {
        "tidyverse" => "r-tidyverse".to_owned(),
        "lme4" => "r-lme4".to_owned(),
        "emmeans" => "r-emmeans".to_owned(),
        "broom" => "r-broom".to_owned(),
        "reticulate" => "r-reticulate".to_owned(),
        other => format!("r-{other}"),
    }
}

fn is_source_r_package(package: &str) -> bool {
    let reference = package
        .split_once('=')
        .map(|(_, reference)| reference)
        .unwrap_or(package);
    matches!(
        reference.split_once("::").map(|(source, _)| source),
        Some("cran" | "bioc" | "github")
    )
}

fn conda_r_packages(config: &Config) -> impl Iterator<Item = &str> {
    config
        .r
        .packages
        .iter()
        .filter(|package| !is_source_r_package(package))
        .map(String::as_str)
}

fn source_r_packages(config: &Config) -> Vec<&str> {
    let mut packages = config
        .r
        .packages
        .iter()
        .filter(|package| is_source_r_package(package))
        .map(String::as_str)
        .collect::<Vec<_>>();
    packages.sort_unstable();
    packages
}

fn r_package_name(package: &str) -> Option<String> {
    if let Some((name, reference)) = package.split_once('=') {
        if is_source_r_package(reference) {
            return Some(name.to_owned());
        }
    }

    let (source, reference) = match package.split_once("::") {
        Some(parts) => parts,
        None => return Some(package.to_owned()),
    };
    match source {
        "cran" | "bioc" => reference
            .split(['@', '?'])
            .next()
            .filter(|name| !name.is_empty())
            .map(str::to_owned),
        "github" => reference
            .split(['@', '#', '?'])
            .next()
            .and_then(|repository| repository.split('/').nth(1))
            .map(|repository| repository.trim_end_matches(".git"))
            .filter(|name| !name.is_empty())
            .map(str::to_owned),
        _ => None,
    }
}

fn known_r_mapping(package: &str) -> bool {
    matches!(
        package.to_ascii_lowercase().as_str(),
        "tidyverse" | "lme4" | "emmeans" | "broom" | "reticulate"
    )
}

fn should_use_locked_install(lock_exists: bool, refresh: bool) -> bool {
    lock_exists && !refresh
}

fn escape_r_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "\\'")
}

fn r_string_literal(value: &str) -> String {
    format!("'{}'", escape_r_string(value))
}

fn read_dual_lock(path: &Path) -> Result<DualLock> {
    let lock: DualLock = serde_json::from_slice(
        &fs::read(path).with_context(|| format!("could not read {}", path.display()))?,
    )
    .with_context(|| {
        format!(
            "{} is not a supported dual lockfile; run `dual up --refresh`",
            path.display()
        )
    })?;
    if lock.version != 1 {
        anyhow::bail!("{} uses an unsupported lockfile version", path.display());
    }
    Ok(lock)
}

fn read_json(path: &Path) -> Result<serde_json::Value> {
    serde_json::from_slice(
        &fs::read(path).with_context(|| format!("could not read {}", path.display()))?,
    )
    .with_context(|| format!("could not parse {}", path.display()))
}

fn write_json(path: &Path, value: &impl Serialize) -> Result<()> {
    let mut contents = serde_json::to_vec_pretty(value)?;
    contents.push(b'\n');
    fs::write(path, contents).with_context(|| format!("could not write {}", path.display()))
}

fn write_dual_lock(path: &Path, lock: &DualLock) -> Result<()> {
    let temporary = path.with_extension(format!("lock.tmp-{}", unique_suffix()));
    write_json(&temporary, lock)?;
    #[cfg(windows)]
    if path.is_file() {
        fs::remove_file(path)?;
    }
    fs::rename(&temporary, path).with_context(|| format!("could not update {}", path.display()))
}

fn default_dual_home() -> PathBuf {
    #[cfg(windows)]
    {
        env::var_os("LOCALAPPDATA")
            .or_else(|| env::var_os("USERPROFILE"))
            .map(PathBuf::from)
            .unwrap_or_else(env::temp_dir)
            .join("dual")
    }

    #[cfg(not(windows))]
    {
        env::var_os("HOME")
            .map(PathBuf::from)
            .unwrap_or_else(env::temp_dir)
            .join(".dual")
    }
}

fn engine_binary_name() -> &'static str {
    if cfg!(windows) {
        "dual-engine.exe"
    } else {
        "dual-engine"
    }
}

struct EngineAsset {
    url: String,
    sha256: &'static str,
}

fn engine_asset() -> Result<EngineAsset> {
    let base = format!("https://github.com/prefix-dev/pixi/releases/download/v{ENGINE_VERSION}");
    let (name, sha256) = match (env::consts::OS, env::consts::ARCH) {
        ("macos", "aarch64") => (
            "pixi-aarch64-apple-darwin",
            "413b3f3e9fa73957b3f8b03734917f94e4763c791b7fa97187906e7f023e88d2",
        ),
        ("macos", "x86_64") => (
            "pixi-x86_64-apple-darwin",
            "2afcd3001e0db69c53cd9ffa9495c292e43947529acb50780693f059d1352cb3",
        ),
        ("linux", "aarch64") => (
            "pixi-aarch64-unknown-linux-musl",
            "bcc3f3e11b4c59a4370cfb749822367489aa2257e9d730daee18980415412136",
        ),
        ("linux", "x86_64") => (
            "pixi-x86_64-unknown-linux-musl",
            "e10db390cc6d68f7a16ec6960fb3a8f9fcd346edf9e41a1e45f58fb44d80df95",
        ),
        ("windows", "aarch64") => (
            "pixi-aarch64-pc-windows-msvc.exe",
            "8ad47aff764ffedf3f4a13d416273f3238641068c70bc1ae17db2a52ad8ee195",
        ),
        ("windows", "x86_64") => (
            "pixi-x86_64-pc-windows-msvc.exe",
            "498e35c5b25526499057076b95dca9636501409f4092484a3e0049fdce380f4b",
        ),
        (os, arch) => anyhow::bail!(
            "Automatic environment support is unavailable for {os}/{arch}. \
             Set DUAL_ENGINE_PATH to a compatible executable."
        ),
    };
    Ok(EngineAsset {
        url: format!("{base}/{name}"),
        sha256,
    })
}

#[cfg(not(windows))]
fn download_file(url: &str, destination: &Path) -> Result<()> {
    let destination = destination.to_string_lossy();
    let curl = Command::new("curl")
        .args(["-fsSL", url, "-o", &destination])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();
    if curl.is_ok_and(|status| status.success()) {
        return Ok(());
    }
    let status = Command::new("wget")
        .args(["-qO", &destination, url])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .context("neither curl nor wget could download environment support")?;
    if status.success() {
        Ok(())
    } else {
        anyhow::bail!("environment support download failed")
    }
}

#[cfg(windows)]
fn download_file(url: &str, destination: &Path) -> Result<()> {
    let script = format!(
        "$ErrorActionPreference='Stop'; Invoke-WebRequest -UseBasicParsing -Uri {url:?} -OutFile {path:?}",
        path = destination.to_string_lossy()
    );
    let status = Command::new("powershell.exe")
        .args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command"])
        .arg(script)
        .status()
        .context("PowerShell could not download environment support")?;
    if status.success() {
        Ok(())
    } else {
        anyhow::bail!("environment support download failed")
    }
}

fn sha256_file(path: &Path) -> Result<String> {
    let mut file = fs::File::open(path)?;
    let mut hasher = Sha256::new();
    let mut buffer = [0_u8; 64 * 1024];
    loop {
        let read = file.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
    }
    Ok(format!("{:x}", hasher.finalize()))
}

fn sanitized_engine_error(bytes: &[u8]) -> String {
    String::from_utf8_lossy(bytes)
        .lines()
        .filter(|line| !line.trim().is_empty())
        .take(12)
        .map(|line| {
            line.replace("pixi", "environment engine")
                .replace("Pixi", "Environment engine")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn sanitized_task_stderr(bytes: &[u8]) -> String {
    String::from_utf8_lossy(bytes)
        .lines()
        .filter(|line| !line.contains("Pixi task") && !line.contains("pixi task"))
        .map(|line| {
            line.replace("pixi", "environment engine")
                .replace("Pixi", "Environment engine")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn unique_suffix() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or_default()
}

fn clear_engine_markers(root: &Path) -> Result<()> {
    if !root.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if matches!(
            name.as_ref(),
            ".pixi" | "pixi" | "pixi_env_prefix" | ".pixi-environment-fingerprint" | "pixi.lock"
        ) {
            if file_type.is_dir() {
                fs::remove_dir_all(path)?;
            } else {
                fs::remove_file(path)?;
            }
        } else if file_type.is_dir() {
            clear_engine_markers(&path)?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use crate::config::{LanguageConfig, ProjectConfig};

    use super::*;

    fn sample_config() -> Config {
        Config {
            project: ProjectConfig {
                name: "mixed".into(),
            },
            r: LanguageConfig {
                version: "4.5".into(),
                packages: vec![
                    "tidyverse".into(),
                    "emmeans".into(),
                    "cran::targets@1.11.4".into(),
                    "bioc::DESeq2".into(),
                    "custom=github::owner/repository@abc123".into(),
                ],
            },
            python: LanguageConfig {
                version: "3.12".into(),
                packages: vec!["pandas".into(), "scikit-learn".into()],
            },
            tasks: BTreeMap::from([("analysis".into(), "Rscript scripts/analysis.R".into())]),
        }
    }

    #[test]
    fn generated_manifest_contains_expected_dependencies() {
        let manifest = generate_manifest(&sample_config()).unwrap();
        assert!(manifest.starts_with("# This file is generated by dual."));
        assert!(manifest.contains("r-tidyverse"));
        assert!(manifest.contains("r-emmeans"));
        assert!(manifest.contains("r-pak"));
        assert!(!manifest.contains("r-targets"));
        assert!(!manifest.contains("r-deseq2"));
        assert!(!manifest.contains("r-custom"));
        assert!(manifest.contains("[tool.pixi.pypi-dependencies]"));
        assert!(manifest.contains("pandas"));
        assert!(manifest.contains("scikit-learn"));
        assert!(manifest.contains("osx-arm64"));
        assert!(manifest.contains("[tool.pixi.tasks.analysis]"));
        assert!(manifest.contains("cmd = \"Rscript scripts/analysis.R\""));
        assert!(manifest.contains("cwd = \"../..\""));
        assert!(manifest.contains("[tool.pixi.target.unix.activation.env]"));
        assert!(
            manifest.contains("RETICULATE_PYTHON = \"$PIXI_PROJECT_ROOT/../bridge/bin/python\"")
        );
        assert!(manifest.contains("RETICULATE_USE_MANAGED_VENV = \"no\""));
        assert!(manifest.contains("[tool.pixi.target.win.activation.env]"));
    }

    #[test]
    fn generated_manifest_supports_python_versions_and_extras() {
        let mut config = sample_config();
        config.python.packages = vec!["pandas>=2,<3".into(), "requests[socks]==2.32.3".into()];
        let manifest = generate_manifest(&config).unwrap();
        assert!(manifest.contains("pandas = \">=2,<3\""));
        assert!(manifest.contains("[tool.pixi.pypi-dependencies.requests]"));
        assert!(manifest.contains("version = \"==2.32.3\""));
        assert!(manifest.contains("extras = [\"socks\"]"));
    }

    #[test]
    fn shared_lock_is_enforced_when_manifest_is_regenerated() {
        assert!(should_use_locked_install(true, false));
    }

    #[test]
    fn refresh_explicitly_updates_shared_lock() {
        assert!(!should_use_locked_install(true, true));
    }

    #[test]
    fn first_install_creates_a_lock() {
        assert!(!should_use_locked_install(false, false));
    }

    #[test]
    fn recognizes_supported_r_source_references() {
        assert!(is_source_r_package("cran::targets"));
        assert!(is_source_r_package("bioc::DESeq2"));
        assert!(is_source_r_package("github::r-lib/pak@v0.9.0"));
        assert!(is_source_r_package(
            "pkg=github::organization/repository@abc123"
        ));
        assert!(!is_source_r_package("tidyverse"));
    }

    #[test]
    fn extracts_installable_r_package_names() {
        assert_eq!(
            r_package_name("cran::targets@1.11.4").as_deref(),
            Some("targets")
        );
        assert_eq!(r_package_name("bioc::DESeq2").as_deref(), Some("DESeq2"));
        assert_eq!(
            r_package_name("github::r-lib/pak@v0.9.0").as_deref(),
            Some("pak")
        );
        assert_eq!(
            r_package_name("github::organization/repository/subdir@abc123").as_deref(),
            Some("repository")
        );
        assert_eq!(
            r_package_name("actual=github::owner/repository@abc123").as_deref(),
            Some("actual")
        );
    }

    #[test]
    fn dual_lock_round_trips_all_resolutions() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("dual.lock");
        let expected = DualLock {
            version: 1,
            environment: "version: 6\n".into(),
            r: Some(RSourceLock {
                sources: vec![
                    "cran::targets@1.11.4".into(),
                    "github::r-lib/pak@v0.9.0".into(),
                ],
                pak: serde_json::json!({"lockfile_version": "1.0.0"}),
            }),
        };

        write_dual_lock(&path, &expected).unwrap();
        let actual = read_dual_lock(&path).unwrap();

        assert_eq!(actual.version, 1);
        assert_eq!(actual.environment, expected.environment);
        assert_eq!(
            actual.r.as_ref().unwrap().sources,
            expected.r.as_ref().unwrap().sources
        );
        assert_eq!(
            actual.r.as_ref().unwrap().pak,
            expected.r.as_ref().unwrap().pak
        );
    }

    #[test]
    fn reads_legacy_lock_field_but_writes_neutral_field() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("dual.lock");
        fs::write(&path, r#"{"version":1,"pixi":"legacy"}"#).unwrap();
        let lock = read_dual_lock(&path).unwrap();
        assert_eq!(lock.environment, "legacy");
        write_dual_lock(&path, &lock).unwrap();
        let contents = fs::read_to_string(path).unwrap();
        assert!(contents.contains("\"environment\""));
        assert!(!contents.contains("\"pixi\""));
    }

    #[test]
    fn removes_private_engine_marker_names() {
        let directory = tempfile::tempdir().unwrap();
        let metadata = directory.path().join("env/conda-meta");
        fs::create_dir_all(metadata.join(".pixi")).unwrap();
        for name in [
            "pixi",
            "pixi_env_prefix",
            ".pixi-environment-fingerprint",
            "pixi.lock",
        ] {
            fs::write(metadata.join(name), "marker").unwrap();
        }
        fs::write(metadata.join("history"), "keep").unwrap();

        clear_engine_markers(directory.path()).unwrap();

        assert!(metadata.join("history").is_file());
        assert!(!metadata.join(".pixi").exists());
        assert!(!metadata.join("pixi").exists());
        assert!(!metadata.join("pixi_env_prefix").exists());
        assert!(!metadata.join(".pixi-environment-fingerprint").exists());
        assert!(!metadata.join("pixi.lock").exists());
    }
}
