use clap::{Parser, Subcommand, ValueEnum};

#[derive(Debug, Parser)]
#[command(
    name = "dual",
    version,
    about = "Reproducible R and Python projects without environment-tool busywork",
    long_about = "dual coordinates a reproducible project environment for R, Python, or both. \
                  Edit dual.toml; dual handles the environment."
)]
pub struct Cli {
    /// Show additional environment progress.
    #[arg(long, global = true)]
    pub verbose: bool,

    #[command(subcommand)]
    pub command: Commands,
}

#[derive(Debug, Subcommand)]
pub enum Commands {
    /// Create dual.toml and standard project directories.
    Init {
        /// Replace an existing dual.toml.
        #[arg(long)]
        force: bool,

        /// Override the project name inferred from the directory.
        #[arg(long)]
        name: Option<String>,
    },

    /// Add packages to dual.toml.
    Add {
        /// Package ecosystem: r or py.
        #[arg(value_enum)]
        language: Language,

        /// One or more package names.
        #[arg(required = true, num_args = 1..)]
        packages: Vec<String>,
    },

    /// Remove packages from dual.toml.
    Remove {
        /// Package ecosystem: r or py.
        #[arg(value_enum)]
        language: Language,

        /// One or more package names.
        #[arg(required = true, num_args = 1..)]
        packages: Vec<String>,
    },

    /// Create or update the project environment.
    Up {
        /// Re-resolve dependencies and update dual.lock.
        #[arg(long)]
        refresh: bool,
    },

    /// Run a named task inside the project environment.
    Run {
        /// Task name from [tasks] in dual.toml.
        task: String,
    },

    /// Inspect configured tasks.
    Task {
        #[command(subcommand)]
        command: TaskCommand,
    },

    /// Manage dual's private environment support.
    Engine {
        #[command(subcommand)]
        command: EngineCommand,
    },

    /// Manage the dual lockfile.
    Lock {
        #[command(subcommand)]
        command: LockCommand,
    },

    /// Open an interactive shell inside the project environment.
    Shell,

    /// Diagnose configuration, environment, packages, and tasks.
    Doctor,

    /// Remove files and environments generated by dual.
    Clean {
        /// Skip the confirmation prompt.
        #[arg(long, short = 'y')]
        yes: bool,
    },
}

#[derive(Debug, Subcommand)]
pub enum TaskCommand {
    /// List configured tasks.
    List,
}

#[derive(Debug, Subcommand)]
pub enum EngineCommand {
    /// Download and activate the currently pinned engine version.
    Update,

    /// Remove dual's private engine installation.
    Uninstall,
}

#[derive(Debug, Subcommand)]
pub enum LockCommand {
    /// Rewrite dual.lock using the current lockfile format.
    Migrate,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
pub enum Language {
    R,
    #[value(alias = "python")]
    Py,
}
